# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Wy56hGCFX0B4PMP6cnYo_FjsFV_B085
"""

import pandas as pd

j1 = {
    "familiya": ["Abdusalimov", "Bekmuhammedov", "Ne'matillayev", "Maxsudov", "Yusupov", "Raxmatov"],
    "Ism": ["Muhammadali", "Ibrohimjon", "Rahmonjon", "inomjon", "Dilyorbek", "Nurbek"],
    "yoshi": [20, 22, 20, 20, 20, 20],
    "manzili": ["Farg'ona", "Quvasoy", "Andijon", "qo'qon", "Farg'ona", "Andijon"]
}

df = pd.DataFrame(j1)

print(df)

df["telefon raqami"]=["994824756","778945612",'701247545','931567489','500507248','941231564']
df

print(df[["Ism","telefon raqami"]])

#jadval boshidan n ta satriga murojaat
df.head(3)

#ustun nomlar
df.columns

#jadvalni oxiriga murojat
df.tail(1)

df.shape

df.sort_values(by='yoshi',ascending=False)

df["tug'ilgan kuni"]=["2005","2003",'2005','2005','2005','2005']
df

df = df.sort_values(by='yoshi', ascending=True)
df